### ISSUE TITLE
Installation with executable failing 

### ISSUE THREAD

**Issue by lidialuq** [rordenlab/dcm2niix#474]
I am not able to install dcm2niix by using the .zip executable. Using the command `pip install dcm2niix_win.zip ` on windows I get the following output:

```
Processing c:\users\sovn\downloads\dcm2niix_win.zip
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\sovn\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sovn\\AppData\\Local\\Temp\\pip-req-build-g9f13kqw\\setup.py'"'"'; __file__='"'"'C:\\Users\\sovn\\AppData\\Local\\Temp\\pip-req-build-g9f13kqw\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\sovn\AppData\Local\Temp\pip-pip-egg-info-2j6qvr5k'
         cwd: C:\Users\sovn\AppData\Local\Temp\pip-req-build-g9f13kqw\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\sovn\appdata\local\programs\python\python39\lib\tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sovn\\AppData\\Local\\Temp\\pip-req-build-g9f13kqw\\setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I am using the last stable release (v1.0.20201102)

**Comment by neurolabusc** [comment]
dcm2niix is a stand alone executable distributed as a zip archive, it is not a Python script installed with pip. You can `download`, `extract` and `run` dcm2niix with the following commands:

```
curl -fLO https://github.com/rordenlab/dcm2niix/releases/latest/download/dcm2niix_win.zip
tar -xf dcm2niix_win.zip
dcm2niix
```

**Comment by hanayik** [comment]
@lidialuq and @neurolabusc, you can also install dcm2niix with conda (a package manager written in python) if that fits better with your python/pip way of working and keeping track of packages. 

`conda install -c conda-forge dcm2niix`
